# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: municipalitypass
      POSTGRES_DB: municipality_db
      PGPORT: 5433 # Forces PostgreSQL to change its internal port
    ports:
      - "5433:5433" # Windows Host (5433) | Inside Docker (5433)
    volumes:
      - pgdata:/var/lib/postgresql/data
      # This automatically runs your schema.sql to set up the tables on the first run!
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  backend:
    build:
      context: ./backend
    container_name: node_backend
    ports:
      - "3000:3000" # Change left side if you want a different host port
    depends_on:
      - db
    env_file:
      - ./backend/.env # Passes your existing .env file into the container

  frontend:
    build:
      context: ./frontend
    container_name: react_ionic_frontend
    ports:
      - "8080:8080" # Access frontend at http://localhost:8080
    depends_on:
      - backend

volumes:
  pgdata: